query Serviceext($query: ClaimServiceLineExtensionQuery)
{
    metadata: claimServiceLineExtensionsMetadata(query: $query)
    {
        totalCount
        page
        pageSize
    }
    claimServiceLineExtensions(query: $query)
    {

        claimServiceLineIdentifier
        claimTransactionIdentifier
        sourceSystemCode
        lineProviderWriteOff
        ub92ProcedureCode
        closure1Code
        closure2Code
        closure3Code
        closure4Code
        pharmacyCouponStatusCode
        timelyFileLimitValue
        timelyFileTypeCode
        prsRemarkCode
        timelyFileLimitValue
        remarkCode2
        lineFinalCauseCode

        claimLineAdditionalInfo
        {
            additionalInformationsequenceNbr
            claimType
            expandedOriginalclaimNumber
            killDeleteIndicator
            killDeleteReasonCode
            reconsiderationTrackingnumber
        }
        linePaymentInfo
        {
            checkSeriesDesignatorCode
            paymentAmount
            paymentEffectiveDate
            paymentNumber
        }


        lineProviderInfo
        {
            providerProductCode
            providerMarketTypecode
            providerMarketNumber
            providerIpaIndicator
            providerTierIndicator
            providerTaxPrefixSuffixIdentifier
            providerSequenceCode
            addressText1
            addressText2
            city
            cliaNumber
            postalcode
            providerProductCode
            providerAddressSequenceNumber
            providerEobName
            providerFirstName
            providerLastName
            providerMedicalNecessityIndicator
            providerMiddleName
            providerMpinIdentifier
            providerName
            providerParticipatingIndicator
            providerQualificationCode
            providerTaxPrefixSuffixIdentifier
            providerTelephoneNumber
            providerTypeCode
            provider2Name
            state
            UB92facilityContributionMethod
            UB92facilityContributionTransit
        }
        anesthesiaMinimumnumber
        authorizedProcedureCode
        baseWouldPayAmount
        billDayUnitNumber
        capitatedCode
        capitatedFundTypeCode
        lbmLineIncludeCode
        cobIndicator
        coinsuranceAfterCouponAmount
        contractAmount
        deductibleAfterCouponAmount
        hcfaItemcontrolText
        hcfaProceduremodifier1code
        hcfaProceduremodifier2code
        hcfaProceduremodifier3code
        hcfaProceduremodifier4code
        hcfaServiceplaceCode
        informationRemark1Code
        informationRemark2Code
        lbmLineIncludeCode
        lineProviderWriteOff
        majorMedicalWouldPayAmount
        medicaidL04Amount
        medicaidPaidAmount
        medicaidPenaltyAmount
        networkManagementFeeAmount
        notCoveredRemark1Code
        notCoveredRemark2Code
        nysurchargeCoveredmajormedicalAmount
        originalProcedurecode
        originalLineCorrelationIdentifier
        originalLineNumber
        originalPlaceofServicecode
        originalProcedureTypeCode
        originalUnitCount
        otherinsurancePaidLineAmount
        otherinsurancePatientresponsibilityAmount
        payeeCode

        pharmacyCouponAmount
        pharmacyCouponPatientResponsibilityAmount
        physicalMedicineMSKCount
        physicalMedicineMSKIndicator
        physicalMedicineSourceCode
        poolTypeCode
        ppoWitholdPercentage
        procedureCode
        programIdentifiedLastCharacter
        prsCreateSourceCode
        prsDispositionCode
        prsDispositionCode12
        prsRemarkCode
        remarkCode2
        returnCode
        revenueServicedate
        rxNumberIndicator
        sanctionIndicator
        saveNumber
        screenSequenceNumber
        supplementalIndicator
        supplementalWouldPayAmount
        timelyFileLimitValue
        timelyFileTypeCode
        ub92Revenuecode
        ub92Chargeamount
        ub92NotcoveredAmount
        ub92OriginalunitsCount
        ub92Servicedate
        wholeClaimIndicator
    }
}