query Extension($query: ClaimExtensionQuery)
{
    metadata: claimExtensionsMetadata(query: $query) {
        totalCount
        page
        pageSize
    }
    claimExtensions(query: $query)
    {
        sourceSystemCode
        claimTransactionIdentifier
        patientFirstName
        patientLastName
        patientBirthDate
        patientAdrLn1Txt
        patientAdrLn2Txt
        patientCityNm
        patientStCd
        patientZipCd
        participatingNonparticipatingIndicator
        adjudicatedOfficeNumber
        commercialMedicareMedicaidCode
        insuredCertificateNumber
        new835CobProcessingIndicator
        insuredGroupName
        adjudicatedOfficeNumber

        participatingNonparticipatingIndicator
        cobCalculationTypeCode
        claimAdditionalInfo

        {
            claimAdditionalInfoSequence
            expandedOriginalClaimNumber
            claimType
            expandedOriginalClaimNumber
            killDeleteIndicator
            killDeleteReasonCode
            originalClaimNumber
            reconsiderationTrackingNumber
        }

        paymentInfo
        {
            paymentSequenceNo
            checkSeriesDesignatorCode
            checkStatus
            draftNumber
            externalPayerCode
            overpaymentRecoveryAmount
            payeeName
            paymentMethodTypeCode
            paymentAmount
            paymentEffectiveDate
            paymentEnginecheckSeriesDesignatorCode
            paymentEngineTracerNumber
            paymentMethodTypeCode
            paymentModeCode
            paymentNumber
            payVendorIdentifier
        }

        audit{
            sourceSystemCreateDatetime
            sourceSystemUpdateDatetime
        }
        providerInfo
        {
            providerSequenceCode
            providerQualificationCode
            providerTaxIdentificationNumber
            providerSpecialityCode
            providerTierIndicator
            providerMarketTypecode
            providerMarketNumber
            providerIpaIndicator
            providerSequenceCode
            providerIdentifier

            addressText1
            addressText2
            city
            cliaNumber
            postalcode
            providerQualificationCode
            providerFirstName
            providerLastName
            providerGroupName
            providerQualificationCode
            providerMiddleName
            providerMpinIdentifier
            providerNationalProviderIdentifier
            providerQualificationCode
            providerTypeCode
            state
            telephoneNumber
        }


        claimsuffix
        {
            claimSuffixCode
            corresponding835IcnNumber
            selectOrNumber
        }

        actualDraftNumber
        autoAccidentIndicator
        autoAccidentStateCode
        autoAdjudicationIndicator
        claimLevelReasonCode
        claimSubmittedTypeCode
        cobCreditReserveAmount
        commercialMedicareMedicaidCode
        corresponding835draftNbr
        corresponding835IcnNbr
        explanationofbenefitMemberPayMethod
        interestIndicator
        managedcareCreditReserveAmount
        optionOutIndicator
        insuredFirstName
        insuredGroupName
        insuredLastName
        insuredPayerName
        interestChargedAmount
        iplanIndicator
        lbmClaimtypeCode
        medicaidNumber
        medicaidReclamationIndicator
        autoAdjudicationIndicator
        medicalPriorAuthorizationCode
        medicareNumber
        networkManagementFeeAmount
        networkManagementFeePercentage
        nonNetworkRapIndicator
        onshoreOnlyIndicator
        originalInventoryControlNumber
        otherInsurancePaidLineDerivedIndicator
        otherInsuranceParticipatingIndicator
        patientBirthDate
        patientDependentNumber
        patientFirstName
        patientLastName
        patientSocialSecurityNumber
        payLocationCode
        payLocationDivisionCode
        payToEnroleeIndicator
        phiIndicator
        rapsNOBLXRecallIndicator
        receiptLocationCode
        reconsiderationTrackingClaimIdentifier
        splitClaimIndicator
        splitSourceRecordCode
        subscriberBirthDate
        subscriberFirstName
        subscriberLastName
        unitedbehavioralhealthCapitationInd
        unitedfrontendUIDSplitCode
        claimWorkHistory
        {
            batchResolutionDate
            historyCreateDate
            historyPendCode
            historySequenceNumber
            OnlineResolutionDate
        }
    }
}